server:
  port: 8763

spring:
  application:
    name: user-services
  devtools:
    restart:
      enabled: true
      additional-paths: src/main
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
      database: MYSQL
      show-sql: true
      hibernate:
      ddl-auto: update   #validate | update | create | create-drop
  naming:
      strategy: org.hibernate.cfg.DefaultNamingStrategy
  properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect  #Hibernate方言
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  type-aliases-package: com.zsw.dao
  mapper-locations: classpath:mybatis/mapper/*.xml

